Repository moa-moa-service/moamoa-backend, pull requests merged in 2024-01, with the labels that each got.

#2 👷 CI: 배포 자동화 환경 설정
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .ebextensions-release/00-makeFiles.config
  .ebextensions-release/01-set-timezone.config
  .github/workflows/dev-deploy.yml
  .github/workflows/release-deploy.yml
  .platform/nginx.conf
  Procfile
Labels: :construction_worker: infra

#3 🐛 Fix: Release Branch CI 플로우 수정
  .github/workflows/release-deploy.yml
Labels: :bug: bug, :construction_worker: infra, 루크

#4 :bug: Fix: build.gradle 수정
  build.gradle
Labels: :bug: bug, :construction_worker: infra, 루크

#7 :heavy_minus_sign: Chore: Security 의존성 주석 처리
  build.gradle
Labels: :gear: chore, :construction_worker: infra, 루크

#16 ✨ Feat: 인증/인가 구현
  .idea/modules/backend.main.iml
  build.gradle
  src/main/java/site/moamoa/backend/domain/Member.java
  src/main/java/site/moamoa/backend/domain/common/BaseEntity.java
  src/main/java/site/moamoa/backend/domain/embedded/Address.java
  src/main/java/site/moamoa/backend/domain/enums/DeletionStatus.java
  src/main/java/site/moamoa/backend/domain/enums/RoleType.java
  src/main/java/site/moamoa/backend/global/config/SecurityConfig.java
  src/main/java/site/moamoa/backend/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/site/moamoa/backend/global/jwt/service/JwtService.java
  src/main/java/site/moamoa/backend/global/oauth2/CustomOAuth2User.java
  src/main/java/site/moamoa/backend/global/oauth2/OAuthAttributes.java
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/site/moamoa/backend/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/site/moamoa/backend/global/oauth2/userinfo/NaverOAuth2UserInfo.java
  src/main/java/site/moamoa/backend/global/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/site/moamoa/backend/repository/MemberRepository.java
  src/main/java/site/moamoa/backend/web/controller/AuthController.java
  src/main/java/site/moamoa/backend/web/dto/AuthInfoDTO.java
  src/main/java/site/moamoa/backend/web/dto/MemberRequestDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :gear: chore, 머피

#17 ✨ [Feat]: 도메인 구현
  src/main/java/site/moamoa/backend/domain/Category.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/enums/CapacityStatus.java
  src/main/java/site/moamoa/backend/domain/enums/IsAuthorStatus.java
  src/main/java/site/moamoa/backend/domain/mapping/MemberPost.java
  src/main/java/site/moamoa/backend/domain/mapping/PostImage.java
Labels: :construction_worker: infra, 켈리

#18 ✨ Feat:DTO 구현
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/common/BaseEntity.java
  src/main/java/site/moamoa/backend/web/dto/base/KeywordDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/MemberDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/PostDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/SimplePostDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/MemberReqeustDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/PostReqeustDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/KeywordResponseDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/MemberResponseDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/PostResponseDTO.java
Labels: :sparkles: feature, 알렉스

#24 ✨ Feat: Swagger 명세 수정 및 AWS S3 설정 + 리팩토링
  build.gradle
  src/main/java/site/moamoa/backend/aws/s3/AmazonS3Manager.java
  src/main/java/site/moamoa/backend/config/AmazonConfig.java
  src/main/java/site/moamoa/backend/config/SwaggerConfig.java
  src/main/java/site/moamoa/backend/domain/Category.java
  src/main/java/site/moamoa/backend/domain/Member.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/embedded/Address.java
  src/main/java/site/moamoa/backend/domain/mapping/MemberPost.java
  src/main/java/site/moamoa/backend/domain/mapping/PostImage.java
  src/main/java/site/moamoa/backend/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/site/moamoa/backend/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/site/moamoa/backend/web/controller/AuthController.java
  src/main/java/site/moamoa/backend/web/controller/KeywordController.java
  src/main/java/site/moamoa/backend/web/controller/MemberController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/MemberRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/AuthInfoDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/KeywordDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/MemberDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/PostDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/SimplePostDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/MemberReqeustDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/MemberRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/PostReqeustDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/KeywordResponseDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/MemberResponseDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/PostResponseDTO.java
  src/main/resources/application.yml
Labels: :bug: bug, :sparkles: feature, :gear: chore, 루크

#25 🚑 Fix: Health Check 접근 허용
  src/main/java/site/moamoa/backend/global/config/SecurityConfig.java
Labels: :bug: bug, :gear: chore, 루크

#26 ✨ Feat: 공동구매 게시글 조회 API 구현
  build.gradle
  src/main/java/site/moamoa/backend/api_payload/ApiResponseDTO.java
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/api_payload/exception/handler/MemberHandler.java
  src/main/java/site/moamoa/backend/api_payload/exception/handler/PostHandler.java
  src/main/java/site/moamoa/backend/config/QueryDSLConfig.java
  src/main/java/site/moamoa/backend/config/RedisConfig.java
  src/main/java/site/moamoa/backend/config/SwaggerConfig.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/common/BaseEntity.java
  src/main/java/site/moamoa/backend/domain/embedded/Address.java
  src/main/java/site/moamoa/backend/global/config/SecurityConfig.java
  src/main/java/site/moamoa/backend/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/site/moamoa/backend/global/jwt/service/JwtService.java
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/site/moamoa/backend/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/site/moamoa/backend/repository/member/MemberRepository.java
  src/main/java/site/moamoa/backend/repository/post/PostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/post/PostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/repository/post/PostRepository.java
  src/main/java/site/moamoa/backend/service/member/query/MemberQueryService.java
  src/main/java/site/moamoa/backend/service/member/query/MemberQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandService.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/query/PostQueryService.java
  src/main/java/site/moamoa/backend/service/post/query/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/base/PostDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/SimplePostDTO.java
Labels: :sparkles: feature, :gear: chore, 루크

#27 Feat: 사용자 정보 API 구현
  src/main/java/site/moamoa/backend/BackendApplication.java
  src/main/java/site/moamoa/backend/api_payload/code/status/SuccessStatus.java
  src/main/java/site/moamoa/backend/aws/s3/AmazonS3Manager.java
  src/main/java/site/moamoa/backend/config/SwaggerConfig.java
  src/main/java/site/moamoa/backend/converter/MemberConverter.java
  src/main/java/site/moamoa/backend/domain/Member.java
  src/main/java/site/moamoa/backend/domain/common/BaseEntity.java
  src/main/java/site/moamoa/backend/global/config/SecurityConfig.java
  src/main/java/site/moamoa/backend/global/jwt/service/JwtService.java
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/site/moamoa/backend/repository/MemberPostRepository.java
  src/main/java/site/moamoa/backend/service/MemberCommandService.java
  src/main/java/site/moamoa/backend/service/MemberCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/MemberQueryService.java
  src/main/java/site/moamoa/backend/service/MemberQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/MemberController.java
  src/main/java/site/moamoa/backend/web/dto/base/MemberDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/MemberResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor, 머피

#29 ✨ [FEAT]: 키워드로 게시글 조회시 키워드 저장 및 키워드 조회 기능 개발
  build.gradle
  src/main/java/site/moamoa/backend/config/RedisConfig.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/common/BaseEntity.java
  src/main/java/site/moamoa/backend/repository/PostRepository.java
  src/main/java/site/moamoa/backend/service/KeywordService.java
  src/main/java/site/moamoa/backend/service/PostService.java
  src/main/java/site/moamoa/backend/service/RedisService.java
  src/main/java/site/moamoa/backend/web/controller/KeywordController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/resources/application.yml
Labels: :sparkles: feature, 켈리

#34 ♻️ [REFACTOR]: 키워드 검색 횟수 증가 코드 수정 및 TODO 추가
  src/main/generated/site/moamoa/backend/domain/QCategory.java
  src/main/generated/site/moamoa/backend/domain/QMember.java
  src/main/generated/site/moamoa/backend/domain/QPost.java
  src/main/generated/site/moamoa/backend/domain/common/QBaseEntity.java
  src/main/generated/site/moamoa/backend/domain/embedded/QAddress.java
  src/main/generated/site/moamoa/backend/domain/mapping/QMemberPost.java
  src/main/generated/site/moamoa/backend/domain/mapping/QPostImage.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/service/member/command/MemberCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandService.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/query/PostQueryService.java
  src/main/java/site/moamoa/backend/service/post/query/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/test/java/site/moamoa/backend/service/keyword/query/KeywordQueryServiceImplTest.java
Labels: :sparkles: feature, :recycle: refactor, 켈리

#36 ♻️ Refactor: Java 17 버전 통일 및 Convert 코드 리팩토링
  build.gradle
  src/main/java/site/moamoa/backend/config/AmazonConfig.java
  src/main/java/site/moamoa/backend/config/redis/RedisConfig.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/service/post/query/PostQueryServiceImpl.java
  src/main/resources/application.yml
Labels: :gear: chore, :recycle: refactor, :construction_worker: infra, 루크

#37 🚑 Hotfix: List.getFirst() 메소드로 인한 빌드 오류 수정
  src/main/java/site/moamoa/backend/converter/PostConverter.java
Labels: :bug: bug, 루크

#38 ✨ [FEATURE]: 검색어 삭제 API 추가 구현
  src/main/java/site/moamoa/backend/converter/KeywordConverter.java
  src/main/java/site/moamoa/backend/service/keyword/query/KeywordQueryService.java
  src/main/java/site/moamoa/backend/service/keyword/query/KeywordQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/KeywordController.java
  src/main/java/site/moamoa/backend/web/dto/response/KeywordResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor, 켈리

#39 ⚡️Feat: 게시글 등록 및 수정, 공동구매 참여 API 기능 구현
  .idea/modules/backend.main.iml
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/api_payload/exception/handler/CategoryHandler.java
  src/main/java/site/moamoa/backend/api_payload/exception/handler/MemberPostHandler.java
  src/main/java/site/moamoa/backend/converter/member/MemberPostConverter.java
  src/main/java/site/moamoa/backend/converter/post/PostConverter.java
  src/main/java/site/moamoa/backend/converter/postimage/PostImageConverter.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/mapping/PostImage.java
  src/main/java/site/moamoa/backend/global/exception/GeneralException.java
  src/main/java/site/moamoa/backend/repository/category/CategoryRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/MemberPostRepository.java
  src/main/java/site/moamoa/backend/repository/post/PostRepository.java
  src/main/java/site/moamoa/backend/repository/postimage/PostImageRepository.java
  src/main/java/site/moamoa/backend/service/category/query/CategoryQueryService.java
  src/main/java/site/moamoa/backend/service/category/query/CategoryQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/member/query/MemberQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/memberpost/command/MemberPostCommandService.java
  src/main/java/site/moamoa/backend/service/memberpost/command/MemberPostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/memberpost/query/MemberPostQueryService.java
  src/main/java/site/moamoa/backend/service/memberpost/query/MemberPostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandService.java
  src/main/java/site/moamoa/backend/service/post/command/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/post/query/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/postimage/command/PostImageCommandService.java
  src/main/java/site/moamoa/backend/service/postimage/command/PostImageCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/postimage/query/PostImageQueryService.java
  src/main/java/site/moamoa/backend/service/postimage/query/PostImageQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#40 [Refactor]: 사용자 정보 관련 API 기능 테스트 및 코드 개선
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/converter/MemberConverter.java
  src/main/java/site/moamoa/backend/domain/Member.java
  src/main/java/site/moamoa/backend/global/jwt/service/JwtService.java
  src/main/java/site/moamoa/backend/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/site/moamoa/backend/service/member/command/MemberCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/member/query/MemberQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/AuthController.java
  src/main/java/site/moamoa/backend/web/controller/MemberController.java
  src/main/java/site/moamoa/backend/web/dto/response/MemberResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor, 머피

#41 ♻️ Refactor: 개발 완료 API 명세 변경 및 리팩토링
  src/main/java/site/moamoa/backend/service/post/command/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/AuthController.java
  src/main/java/site/moamoa/backend/web/controller/KeywordController.java
  src/main/java/site/moamoa/backend/web/controller/MemberController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :recycle: refactor, 루크
