Repository moa-moa-service/moamoa-backend, pull requests merged in 2024-02, with the labels that each got.

#45 ♻️ [Refactor]: 사용자 정보 관련 API 기능 테스트 및 코드 개선
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/domain/Member.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/global/aws/s3/AmazonS3Manager.java
  src/main/java/site/moamoa/backend/global/jwt/service/JwtService.java
  src/main/java/site/moamoa/backend/global/oauth2/OAuthAttributes.java
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/site/moamoa/backend/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/service/component/command/member/MemberCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/member/MemberCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/member_post/MemberPostCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/category/CategoryQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/member/MemberQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/member/MemberQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/member_post/MemberPostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/post/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/category/CategoryModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member/MemberModuleService.java
  src/main/java/site/moamoa/backend/service/module/member/MemberModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleService.java
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/AuthController.java
  src/main/java/site/moamoa/backend/web/controller/MemberController.java
  src/main/java/site/moamoa/backend/web/dto/request/MemberRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/MemberResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :gear: chore, :recycle: refactor, 머피

#46 :recycle:[Refactor]: 게시물 업데이트 Api 로직 리팩토링
  src/main/java/site/moamoa/backend/converter/MemberPostConverter.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/post_image/PostImageModuleService.java
  src/main/java/site/moamoa/backend/service/module/post_image/PostImageModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/response/PostResponseDTO.java
Labels: :sparkles: feature, :recycle: refactor

#47 ♻️ [REFACTOR]: 검색 키워드 등록 및 조회 API 및 코드 개선
  .idea/modules/backend.main.iml
  src/main/java/site/moamoa/backend/BackendApplication.java
  src/main/java/site/moamoa/backend/service/component/command/keyword/KeywordCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/keyword/KeywordCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/keyword/KeywordQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/keyword/KeywordQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/KeywordController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :recycle: refactor, 켈리

#53 🚑 Hotfix: CORS Config 핫픽스
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
Labels: :bug: bug, :gear: chore, 루크

#54 🚑 Hotfix: CORS 설정 수정 핫픽스
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
Labels: :bug: bug, :gear: chore, 루크

#55 🚑 Hotfix: Redis Health Check 추가
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleService.java
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/RootController.java
Labels: :bug: bug, :construction_worker: infra, 루크

#56 :ambulance: Hotfix: Redis 연결 테스트 추가
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleService.java
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/RootController.java
Labels: :bug: bug, 루크

#58 🚑 Hotfix: Redis Health Check 경로 수정
  src/main/java/site/moamoa/backend/web/controller/RootController.java
Labels: :bug: bug, 루크

#59 :ambulance: Hotfix: Redis 연결 테스트
  src/main/java/site/moamoa/backend/web/controller/RootController.java
  src/main/resources/application.yml
Labels: :bug: bug, 루크

#60 ♻️ Refactor: API 검토 및 수정 필요한 로직 체크
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleService.java
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/CommentController.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/controller/RootController.java
  src/main/resources/application.yml
Labels: :gear: chore, :recycle: refactor, 루크

#61 ✨ Feat: 공지사항 상세조회 API 구현
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/api_payload/exception/handler/NoticeHandler.java
  src/main/java/site/moamoa/backend/converter/CommentConverter.java
  src/main/java/site/moamoa/backend/converter/NoticeConverter.java
  src/main/java/site/moamoa/backend/service/component/query/notice/NoticeQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/notice/NoticeQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/notice/NoticeModuleService.java
  src/main/java/site/moamoa/backend/service/module/notice/NoticeModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/dto/base/NoticeDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/NoticeResponseDTO.java
Labels: :sparkles: feature

#66 ✨ [FEAT]: 공동구매 공지사항 등록 기능 구현
  src/main/java/site/moamoa/backend/converter/NoticeConverter.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/converter/PostImageConverter.java
  src/main/java/site/moamoa/backend/domain/Comment.java
  src/main/java/site/moamoa/backend/domain/Notice.java
  src/main/java/site/moamoa/backend/service/component/command/notice/NoticeCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/notice/NoticeCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/notice/NoticeModuleService.java
  src/main/java/site/moamoa/backend/service/module/notice/NoticeModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/redis/RedisModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/resources/application.yml
Labels: :bug: bug, :sparkles: feature, :recycle: refactor, 켈리

#70 :ambulance: Hotfix: jpa.hibernate.ddl-auto 수정 (#52)
  src/main/resources/application.yml
Labels: :bug: bug, :gear: chore, 루크

#72 🚑 Hotfix: CORS 설정 및 ddl-auto 변경
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: :bug: bug, :gear: chore, 루크

#74 :ambulance: Hotfix: CORS 설정 변경
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
Labels: :bug: bug, :gear: chore, 루크

#67 🐛 Fix: 공동구매 등록 API 요청 바디 수정
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
Labels: :bug: bug

#69 🐛 Fix: 공동구매 상태변경 시, 모집 중으로 상태변경 기능 추가
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :bug: bug

#68 🐛 Fix: 공동구매 수정 요청 시, 수정 사항과 이미지를 분리하여 요청 가능하게 개선
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
Labels: :bug: bug

#77 :ambulance: Hotfix: Spring Security - CORS 재설정
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
Labels: :bug: bug, :recycle: refactor, 루크

#78 :ambulance: Hotfix: Spring Security - CORS 재설정
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
Labels: :bug: bug, :gear: chore, 루크

#71 ♻️ Refactor: 공동구매 상세 조회 기능 수정
  src/main/java/site/moamoa/backend/converter/NoticeConverter.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/repository/post/PostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/notice/NoticeQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/post/PostQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/post/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/base/PostDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/NoticeResponseDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/PostResponseDTO.java
Labels: :gear: chore, :recycle: refactor, 머피

#79 🚑 Hotfix: CORS 수정 최종
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
  src/main/java/site/moamoa/backend/config/swagger/SwaggerConfig.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :bug: bug, :gear: chore, :recycle: refactor, 루크

#75 ✨ Feat: 공동구매 공지사항 댓글/대댓글 등록 API 구현 및 리팩토링
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/api_payload/exception/handler/CommentHandler.java
  src/main/java/site/moamoa/backend/config/SecurityConfig.java
  src/main/java/site/moamoa/backend/converter/CommentConverter.java
  src/main/java/site/moamoa/backend/converter/MemberConverter.java
  src/main/java/site/moamoa/backend/converter/MemberPostConverter.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/domain/Comment.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/mapping/MemberPost.java
  src/main/java/site/moamoa/backend/service/component/command/comment/CommentCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/comment/CommentCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/member/MemberCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/comment/CommentModuleService.java
  src/main/java/site/moamoa/backend/service/module/comment/CommentModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/CommentController.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/base/CommentDTO.java
Labels: :sparkles: feature, :recycle: refactor, 루크

#73 🐛 Fix: 공동구매 참여 시, 게시물 주최자는 참여할 수 없게끔 개선
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
Labels: :bug: bug

#84 :ambulance: Hotfix: OAuth2LoginSuccessHandler 수정
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :bug: bug, :gear: chore, 루크

#85 :ambulance: Hotfix: MemberPostQueryDSLRepositoryImpl 수정
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/repository/post/PostQueryDSLRepositoryImpl.java
Labels: :bug: bug, 루크

#87 :ambulance: Hotfix: 포트 수정
  src/main/java/site/moamoa/backend/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :bug: bug, 루크

#88 ✨ Feat: 알림 생성, 조회 기능 구현
  src/main/generated/site/moamoa/backend/domain/QCategory.java
  src/main/generated/site/moamoa/backend/domain/QComment.java
  src/main/generated/site/moamoa/backend/domain/QMember.java
  src/main/generated/site/moamoa/backend/domain/QNotice.java
  src/main/generated/site/moamoa/backend/domain/QNotification.java
  src/main/generated/site/moamoa/backend/domain/QPost.java
  src/main/generated/site/moamoa/backend/domain/common/QBaseEntity.java
  src/main/generated/site/moamoa/backend/domain/embedded/QAddress.java
  src/main/generated/site/moamoa/backend/domain/mapping/QMemberPost.java
  src/main/generated/site/moamoa/backend/domain/mapping/QPostImage.java
  src/main/java/site/moamoa/backend/converter/NotificationConverter.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/domain/Notification.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/enums/NotificationStatus.java
  src/main/java/site/moamoa/backend/domain/enums/NotificationType.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/repository/notification/NotificationQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/notification/NotificationQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/repository/notification/NotificationRepository.java
  src/main/java/site/moamoa/backend/repository/post/PostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/service/component/command/comment/CommentCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/notice/NoticeCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/notification/NotificationQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/notification/NotificationQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/post/PostQueryService.java
  src/main/java/site/moamoa/backend/service/component/query/post/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/notification/NotificationModuleService.java
  src/main/java/site/moamoa/backend/service/module/notification/NotificationModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/NotificationController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/base/NotificationDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/PostDTO.java
  src/main/java/site/moamoa/backend/web/dto/base/SimplePostDtoWithAddress.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/NotificationResponseDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/PostResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature, 켈리, 알렉스

#89 ♻️ Refactor: 공동구매 참여, 취소, 상세 조회 로직 수정
  src/main/generated/site/moamoa/backend/domain/QCategory.java
  src/main/generated/site/moamoa/backend/domain/QComment.java
  src/main/generated/site/moamoa/backend/domain/QMember.java
  src/main/generated/site/moamoa/backend/domain/QNotice.java
  src/main/generated/site/moamoa/backend/domain/QNotification.java
  src/main/generated/site/moamoa/backend/domain/QPost.java
  src/main/generated/site/moamoa/backend/domain/common/QBaseEntity.java
  src/main/generated/site/moamoa/backend/domain/embedded/QAddress.java
  src/main/generated/site/moamoa/backend/domain/mapping/QMemberPost.java
  src/main/generated/site/moamoa/backend/domain/mapping/QPostImage.java
  src/main/java/site/moamoa/backend/api_payload/code/status/ErrorStatus.java
  src/main/java/site/moamoa/backend/converter/MemberPostConverter.java
  src/main/java/site/moamoa/backend/converter/PostConverter.java
  src/main/java/site/moamoa/backend/domain/Post.java
  src/main/java/site/moamoa/backend/domain/mapping/MemberPost.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostRepository.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/query/post/PostQueryServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/base/SimplePostDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/PostResponseDTO.java
  src/main/resources/application.yml
Labels: :recycle: refactor, 루크

#90 ♻️ [REFACTOR]: unused method, import 삭제
  src/main/java/site/moamoa/backend/converter/NotificationConverter.java
  src/main/java/site/moamoa/backend/domain/enums/NotificationType.java
  src/main/java/site/moamoa/backend/service/component/query/notification/NotificationQueryServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/NotificationController.java
  src/main/java/site/moamoa/backend/web/dto/response/NotificationResponseDTO.java
Labels: :recycle: refactor, 켈리

#91 ♻️ [REFACTOR]: 오타 수정
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/resources/application.yml
Labels: :recycle: refactor, 켈리

#95 ✨ [FEAT]: 공지사항 삭제 및 수정, 알림 기능 구현
  src/main/java/site/moamoa/backend/converter/NoticeConverter.java
  src/main/java/site/moamoa/backend/domain/Notice.java
  src/main/java/site/moamoa/backend/service/component/command/notice/NoticeCommandService.java
  src/main/java/site/moamoa/backend/service/component/command/notice/NoticeCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/notice/NoticeModuleService.java
  src/main/java/site/moamoa/backend/service/module/notice/NoticeModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/notification/NotificationModuleService.java
  src/main/java/site/moamoa/backend/service/module/notification/NotificationModuleServiceImpl.java
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/controller/NotificationController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
  src/main/java/site/moamoa/backend/web/dto/request/NoticeRequestDTO.java
  src/main/java/site/moamoa/backend/web/dto/response/NoticeResponseDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature, 켈리

#96 :bug: Fix: 알림 생성 기능 수정
  src/main/java/site/moamoa/backend/domain/enums/NotificationType.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepository.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/service/component/command/comment/CommentCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleService.java
  src/main/java/site/moamoa/backend/service/module/member_post/MemberPostModuleServiceImpl.java
  src/main/java/site/moamoa/backend/service/module/notification/NotificationModuleService.java
  src/main/java/site/moamoa/backend/service/module/notification/NotificationModuleServiceImpl.java
Labels: :bug: bug

#97 ♻️ Refactor: 알림 로직 구조 개선 및 코드 리팩토링
  src/main/java/site/moamoa/backend/converter/CommentConverter.java
  src/main/java/site/moamoa/backend/converter/NotificationConverter.java
  src/main/java/site/moamoa/backend/domain/Notification.java
  src/main/java/site/moamoa/backend/repository/mapping/member_post/MemberPostQueryDSLRepositoryImpl.java
  src/main/java/site/moamoa/backend/service/component/command/comment/CommentCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/notice/NoticeCommandServiceImpl.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/web/dto/base/CommentDTO.java
Labels: :recycle: refactor, 루크

#98 🚑 Hotfix: Swagger 환경 개선 및 마감 로직, 일부 DTO 필드 추가
  src/main/java/site/moamoa/backend/config/swagger/SwaggerConfig.java
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
  src/main/java/site/moamoa/backend/web/dto/base/SimplePostDTO.java
  src/main/resources/application.yml
Labels: :bug: bug, :gear: chore, :recycle: refactor, 루크

#99 :ambulance: Hotfix: PostConverter 수정
  src/main/java/site/moamoa/backend/converter/PostConverter.java
Labels: :bug: bug, 루크

#100 :ambulance: Hotfix: 댓글 프로필 이미지 추가
  src/main/java/site/moamoa/backend/converter/CommentConverter.java
  src/main/java/site/moamoa/backend/converter/NoticeConverter.java
  src/main/java/site/moamoa/backend/web/dto/base/CommentDTO.java
Labels: :bug: bug, 루크

#101 :ambulance: Hotfix: Swagger 태그 업데이트
  src/main/java/site/moamoa/backend/web/controller/MemberController.java
  src/main/java/site/moamoa/backend/web/controller/PostController.java
Labels: :recycle: refactor, 루크

#102 :ambulance: Hotfix: PostCommandServiceImpl 수정
  src/main/java/site/moamoa/backend/service/component/command/post/PostCommandServiceImpl.java
Labels: :bug: bug, 루크

#103 :ambulance: Hotfix: 오류 수정
  src/main/java/site/moamoa/backend/web/controller/NoticeController.java
  src/main/java/site/moamoa/backend/web/dto/base/PostDTO.java
  src/main/java/site/moamoa/backend/web/dto/request/PostRequestDTO.java
Labels: :bug: bug, 루크
